NAME = libft.a

CC = gcc
CFLAGS = -Wall -Wextra -Werror
AR = ar rcs
RM = rm -f

FILES =

FILES_B =

SRC_DIR = ./
SRCS =
SRCS_B =

OBJS_DIR = ./
OBJS =
OBJS_B =


.c.o: $s(SRCS)
		$(CC) $(CFLAGS) -c -o $@ $<

$(NAME): $(OBJS)
